# Generated by Django 2.1.1 on 2018-09-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_institution'),
        ('accounts', '0002_auto_20180917_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='school_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library.Institution'),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], default=1),
            preserve_default=False,
        ),
    ]
