# Generated by Django 2.1.1 on 2018-11-19 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='department_name',
            new_name='department',
        ),
    ]
