# Generated by Django 2.1 on 2018-08-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180819_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(help_text='MM/DD/YYYY', null=True),
        ),
    ]
